### ISSUE TITLE
회원가입 및 로그인 창 추가(객체로 받아놓고 서버 연결 X)

### ISSUE THREAD

**Issue by Imjungjuna** [skku-comit/comit-website#115]
회원가입과 로그인 창을 만들고 웹사이트에 추가 요망

회원가입 필드: 이름 생일 성별 휴대폰번호 학번 이메일(성대) 비밀번호(+확인)
로그인 필드: 이메일(성대) 비밀번호

**Comment by manamana32321** [comment]
Issues는 주로 해결해야 할 문제를 공유하는 공간입니다.
추가한 코드에 대해서는 Pull request에서 공유되어야 합니다.

이 이슈는 결과 보고에 가까운 성격을 띄는 것 같으니
변경된 코드를 포함하는 branch의 Pull request를 Pull requests 섹션에 올리는 것이 적절해 보입니다.

**Comment by manamana32321** [comment]
확인하시고 해당 Issue close 해주세요!
close 버튼은 이 페이지 하단에 있습니다.

**Comment by Imjungjuna** [comment]
아 아직 완료되지 않은 task를 말한 것이었는데 혼란을 일으킬 만한 문장으로 작성했네요. 수정하였습니다.
