### ISSUE TITLE
스크롤이 내려가 있는 버그 해결

### ISSUE THREAD

**Issue by B0XERCAT** [skku-comit/comit-website#71]
### Describe problem and solution
스크롤을 내려놓은 상태에서 다른 페이지로 이동했을 때
스크롤이 가장 위로 가 있지 않고 살짝 밑으로 가 있음.
다른 페이지로 이동했을 때 스크롤의 가장 위로 이동하도록 수정

**Comment by manamana32321** [comment]
app/(main)/layout.tsx에서 Header 컴포넌트를 주석 처리 했을 때 해당 문제가 발생되지 않음을 확인했습니다.
이를 서버 컴포넌트로 전환하고 최적화하는 등 리팩터링을 한다면 해당 문제를 해결할 수 있을 것이라고 예상됩니다.
