### ISSUE TITLE
Feat: Nav Bar의 현재 URL에 따라 Active하도록 변경해주세요.

### ISSUE THREAD

**Issue by jihostudy** [skku-comit/comit-website#92]
### 현재 상태
위치에 관계없이 Nav Bar의 현재 위치가 어디있지 판단하기 어렵습니다.
![image](https://github.com/user-attachments/assets/6512055e-874a-45b1-8062-00709b6b2f95)

### 예상 상태
URL 위치에 따라 NavBar 색이 바뀌도록 변경해주세요.
![image](https://github.com/user-attachments/assets/1deb0731-0240-43e2-8ea4-d36f58e7c1ff)

**Comment by manamana32321** [comment]
#91 이 병합된 후 해결하겠습니다.
#91 은 이와 관련된 변경 사항이 많기에 추후 병합 시 충돌이 많이 발생 될 것이라고 예상되기 때문입니다.
